### ISSUE TITLE
Clone,configure and build is failing with link issues to fmt

### ISSUE THREAD

**Issue by KartikAiyer** [lefticus/cpp_starter_project#51] opened 2020-04-19 23:12 UTC
Hi Jason,

Thanks a bunch for this starter project and all your videos. 
I cloned the project today and tried to build and ran into a link issue with the fmt library. It compiles fine if I remove the calls to fmt and spdlog. 
I have attached the build output.  I hope I'm not making some rookie mistake.

Thanks again for all your hard work.
[cpp_starter_link_fmt_fail.txt](https://github.com/lefticus/cpp_starter_project/files/4500472/cpp_starter_link_fmt_fail.txt)

EDIT: I'm running pop!os : 19.04 and upgraded cmake to version 17.

**Comment by ddalcino** [comment] 2020-04-21 14:39
You have not made a rookie mistake; this is a long-standing issue with the project that needs to be resolved.
The problem is here, on line 62 of your cmake output:

    WARN: spdlog/1.5.0: requirement fmt/6.1.2 overridden by your conanfile to fmt/6.0.0 

Quick fix: Go to cmake/Conan.cmake and change line 21 to `fmt/6.1.2`; that should resolve this particular issue.

Spdlog 1.5.0 sometimes works with fmt 6.0.0. It worked on @lefticus's setup in his video and in the CI setup. However, it doesn't work for a lot of other people, as you can see below:
https://github.com/lefticus/cpp_weekly_game_project/issues/3
https://github.com/lefticus/cpp_weekly_game_project/issues/10

I have made a pull request that addresses this issue, #35.

Please do not close this issue until the problem is solved in the master branch. People need to be able to find this issue without having to look through cpp_weekly_game_project/issues.

**Comment by lefticus** [comment] 2020-04-22 16:08
I merged #35, it's fixed now

**Closed by lefticus** 2020-04-22 16:08 UTC
